### ISSUE TITLE
OGC API - Tiles - Part 1: Core support

### ISSUE THREAD

**Issue by kolyanch** [sam-is/OgcApi.Net#2]
Implement a standard "OGC API - Tiles - Part 1" (in the draft status) to support fast spatial data publication from databases as MVT (Mapbox Vector Tiles). In addition to the sources in the form of relational databases, it is also necessary to implement the possibility of publishing data from the mbtiles file database, generated by tippecanoe or GDAL.

Draft: http://docs.ogc.org/DRAFTS/20-057.html

**Comment by kolyanch** [comment]
Inner code architecture must satisfy the interface segregation principle to separate Features API and Tiles API.
That means that it is necessary to provide the possibility to create a collection with:
- only features API with full graphics and transactional data modification capabilities
- only vector tiles API with simplified graphics, fast queries, and fast rendering
- both of them

To do that:
- IDataProvider must be renamed to IFeaturesProvider
- Create a separate ITilesProvider interface
- Implement ITilesProvider in new MBTiles provider
- Provide new classes to configure Tiles API (options pattern)

Also, the current structure of the solution and packages does not satisfy current conditions.
Therefore it is better to rename projects and packages, not mention Features.

At the first implementation stage, it is necessary to implement a data provider from the MBTiles data format.
Tiles, in this case, are considered pre-made. 

Dynamic tile generation based on the data from databases is the task for the subsequent releases. Also, other data providers for the tiles publishing are in plans.

**Comment by bam-samis** [comment]
ITilesProvider interface is designed and MBTiles data provider is implemented. API options restructured, now each collection have separate settings for tiles and features. Previously implemented projects classes and interfaces are renamed and arranged according to the new structure. Project is published.
