### ISSUE TITLE
Collection request is too slow on large mbtiles file size

### ISSUE THREAD

**Issue by kolyanch** [sam-is/OgcApi.Net#32]
SQL command used to get tiles limits is too slow on large datasets. Rewrite GetLimits method to analyze mbtiles file size or fully abandon this calculation and make the tile limits definition optional at the settings level.

**Comment by bam-samis** [comment]
The tile matrix limits are now calculated by the minzoom, maxzoom, and boundbox values obtained from the "metadata" table instead of grouping the data from the "tiles" table. Accordingly, the speed of tile matrix limits calculation does not depend on the size of the dataset.
