### ISSUE TITLE
OGC API Tiles: Add authentication support

### ISSUE THREAD

**Issue by kolyanch** [sam-is/OgcApi.Net#38]
Authentication can be done by API key. The task is to restrict access to tiles when specifying a key. The major problem is how to verify the key.

**Comment by bam-samis** [comment]
Added support for tiles access delegate by apiKey, collectionId, tileMatrix, tileRow and tileCol. Implementing this delegetate allow to control user access for tiles by user, territory and feature collection.

`public delegate bool TileAccessDelegate(string collectionId, int tileMatrix, int tileRow, int tileCol, string apiKey);`

The delegate is called from the API controller.
